title:              DevBlog
email:              leejingeol@gmail.com
description:        개발 블로그
author:             leejingeol
baseurl:            ""
url:                "https://leejingeol.github.io"

# Social Profiles
twitter_username:   
github_username:    leejingeol
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

disqus_shortname: leejingeol
comments: true